-
  name: 'Authenticate'
  uriPattern: 'authenticate'
  appendExceedingArguments: true
  defaults:
    '@package':    'Refactory.Login'
    '@controller': 'Login'
    '@action':     'authenticate'
    '@format':     'json'